openapi: 3.0.0
info:
  title: Bulk Syncs
  version: 1.0.0
servers:
  - url: 'https://api.theknowable.com'
paths:
  /projects/b54bb945-184d-4e1d-aaad-2e8641a9908e/overlay:
    $ref: paths/projects@b54bb945-184d-4e1d-aaad-2e8641a9908e@overlay.yaml
  /projects/7bce747b-1139-478e-a5a9-b77ad7492e22/review-status:
    $ref: paths/projects@7bce747b-1139-478e-a5a9-b77ad7492e22@review-status.yaml
